const advancedTopics = [
  "Verbs",
  "Personal Pronouns",
  "Prepositions",
  "Tenses",
  "Adjectives",
  "Degree of Comparison",
  "Modal Auxiliaries",
  "General Topics",
  "Question Tags",
  "Vocabularies",
  "Passive Voice",
  "Nouns",
  "Relative Pronouns",
  "Conjunctions",
  "Indefinite Pronouns",
  "Causative (Causal Verbs)",
  "Phrasal Verbs",
  "Adverbs",
  "Gerunds",
  "Infinitives",
  "Interjection",
  "Email and Letter Writing",
  "Group Discussion",
  "Speaking Practice",
  "Conversation",
  "Interview Preparation",
];
export default advancedTopics;